task:
    path:     /
    defaults: { _controller: "ProjecttodoBundle:Task:index" }

task_show:
    path:     /{id}/show
    defaults: { _controller: "ProjecttodoBundle:Task:show" }

task_new:
    path:     /new
    defaults: { _controller: "ProjecttodoBundle:Task:new" }

task_create:
    path:     /create
    defaults: { _controller: "ProjecttodoBundle:Task:create" }
    requirements: { _method: post }

task_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProjecttodoBundle:Task:edit" }

task_update:
    path:     /{id}/update
    defaults: { _controller: "ProjecttodoBundle:Task:update" }
    requirements: { _method: post|put }

task_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProjecttodoBundle:Task:delete" }
    requirements: { _method: post|delete }
