parameters:
#    projecttodo.example.class: Project\todoBundle\Example

services:
#    projecttodo.example:
#        class: %projecttodo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
